spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  spring:
    mail:
      host: smtp.example.com
      port: 587
      username: vacnelan70@gmail.com
      password: zxpt ehea qjlj aeio
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true


server:
  error:
    include-message: always
